{% set name = "nyxtools" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nyxtools-{{ version }}.tar.gz
  sha256: 5240802d55fcb7f2f7f31037e80bd8ddf9bbafc470a853aa9e7f7fcab9857d65

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - area-detector-handlers
    - mxtools

test:
  imports:
    - nyxtools
    - nyxtools.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NSLS-II-NYX/nyxtools
  summary: Common code for the NYX beamline at NSLS-II.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JunAishima
    - mrakitin
