{% set name = "nyxtools" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nyxtools-{{ version }}.tar.gz
  sha256: 5f2eefae49d3fb62d6bb1b0e03c0a0f33c50d1a0b7db50445be2bacfb676e573

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - area-detector-handlers
    - mxtools
    - fabio

test:
  imports:
    - nyxtools
    - nyxtools.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NSLS-II-NYX/nyxtools
  summary: Common code for the NYX beamline at NSLS-II.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JunAishima
    - mrakitin
